### ISSUE TITLE
submission查看报错了

### ISSUE THREAD

**Issue by fanjunzhi** [lutece-awesome/lutece-frontend#113]
connection.js:8 WebSocket connection to 'wss://acm.uestc.edu.cn/ws/status/86627/?eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImZhbmp1bnpoaSIsImV4cCI6MTU3MzYwOTk0OCwib3JpZ0lhdCI6MTU3MzU1NDg5OSwicGFzc3dvcmQiOiJoTnk0cHlrPSJ9.44cDTvFwvs64EmvQkIfdshqo6nOaacE_wyA-Oik7Zas' failed: Error during WebSocket handshake: Unexpected response code: 200
(anonymous) @ connection.js:8
x @ es6.promise.js:177
ha @ connection.js:5
start @ detail.vue:173
pk @ detail.vue:141
nr.run @ vue.runtime.esm.js:4562
Wn @ vue.runtime.esm.js:4304
(anonymous) @ vue.runtime.esm.js:1980
se @ vue.runtime.esm.js:1906
a @ es6.promise.js:75
(anonymous) @ es6.promise.js:92
s @ _microtask.js:18

**Comment by zhz** [comment]
websocket 服务应该是挂掉了，只能等管理员重启了

`daphne -u /tmp/daphne.sock Lutece.asgi:application &`

```
#websocket
	location /ws {
 		proxy_pass http://unix:/tmp/daphne.sock;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_redirect off;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $server_name;
	}
```
