### ISSUE TITLE
需求：在user排名界面增加签名显示

### ISSUE THREAD

**Issue by qscqesze** [lutece-awesome/lutece-frontend#12]
![image](https://user-images.githubusercontent.com/7346749/46855935-a9acd700-ce37-11e8-8ddc-85c9a25e69d3.png)

个人认为签名是很好展现自信的地方，增加签名显示会更加exciting一点

**Comment by LaPluses** [comment]
In fact, the free space in data table is tighty, i think add new column to show about info may not a good choice.
