### ISSUE TITLE
Problem search fails in status page

### ISSUE THREAD

**Issue by Fragile-azalea** [lutece-awesome/lutece-frontend#14]
![image](https://user-images.githubusercontent.com/17422499/48670761-5de8fe00-eb58-11e8-83e4-76e605e9a356.png)

**Comment by LaPluses** [comment]
Fixed in <a href = "https://github.com/lutece-awesome/lutece-backend/commit/380282dd360a4b5151e5c0bf232df5f2f25cd6d3#diff-b5277cc37b6c04e4fec3f48b11864067R35"> CL </a>.

+ Waiting for deploying.

**Comment by LaPluses** [comment]
Fixed in 0.1.2 release version.

+ 7c31d12
