### ISSUE TITLE
页面响应

### ISSUE THREAD

**Issue by 599218113** [lutece-awesome/lutece-frontend#53]
除contest外其余页面可以正常响应。
进入contest的loading超过5min。

**Comment by 599218113** [comment]
upd: 使用的是平板电脑的浏览器

**Comment by LaPluses** [comment]
请问能提供一下具体的数据吗？包括
* 使用的平板
* 在平板上的浏览器和具体的版本号?

**Comment by 599218113** [comment]
- 小米3平板电脑
- 小米浏览器（即系统自带的浏览器）version:10.2.11
- 经测试 firefox 和 chorme 可以正常打开，大概是浏览器的问题x

**Comment by LaPluses** [comment]
这个可能是小米自带浏览器Webview的问题，使用Chrome | Firefox即可.
