### ISSUE TITLE
Some user experience issues

### ISSUE THREAD

**Issue by HeRaNO** [lutece-awesome/lutece-frontend#54]
1. After submitting a problem, there's no way to jump to the contest page directly...
2. The rank page seems having bugs.
At the same time, Chrome show this page like this:

![图片](https://coding.net/u/HeRaNO/p/PicPlace/git/raw/master/lutece_issue1.png)

But Firefox show this page like this:

![图片](https://coding.net/u/HeRaNO/p/PicPlace/git/raw/master/lutece_issue2.png)

And the two ways are all wrong.

Looking forward to fixing.

**Comment by LaPluses** [comment]
Thanks for your detail feedback, for the first one, I would rewrite those logic on both front & back end, hope to use dialog to show the status of submission within contest, for the second one, as current Lutece contest ranking are completely processed by frontend, which is much different from others OJ, for example, the Codeforces' contest rank page is rendered by back end, but for the current design would reduce the pressure of server, but there is a risk that final rendering results on different browsers may different, i would double check it.

**Comment by HeRaNO** [comment]
Many thanks 👍

**Comment by LaPluses** [comment]
Fixed.
