### ISSUE TITLE
bug:user界面的通过率计算不对

### ISSUE THREAD

**Issue by qscqesze** [lutece-awesome/lutece-frontend#6]
![image](https://user-images.githubusercontent.com/7346749/46712022-8dffd000-cc81-11e8-9561-04203c2abc8f.png)

理论上用户qscqesze的通过率为100%，但实际上计算的时候算上了曾经通过的这道题之后wa的ratio，和左边不一致了？
建议通过率直接用  通过的题数／总提交的题数 而不是采用 ac的提交数／总提交数

**Comment by LaPluses** [comment]
实际上无论是Codechef还是Leetcode，对于通过率都是这样计算的.
[https://www.codechef.com/users/xiper](url)
[https://leetcode.com/xiper/](url)
