### ISSUE TITLE
需求: status页面进去后，提交状况加个颜色

### ISSUE THREAD

**Issue by qscqesze** [lutece-awesome/lutece-frontend#7]
![image](https://user-images.githubusercontent.com/7346749/46712251-aae8d300-cc82-11e8-99f6-4baf484a2660.png)
如图，建议accept变成绿色，wa是红色这种。

全是黑色的很蛋疼

**Comment by LaPluses** [comment]
Added in 7998b05c3f57491a082b86630b10f5f64f25db0a
