### ISSUE TITLE
需求：和之前cdoj的markdown语法不一致，是否需要做适配？

### ISSUE THREAD

**Issue by qscqesze** [lutece-awesome/lutece-frontend#8]
![image](https://user-images.githubusercontent.com/7346749/46712342-29457500-cc83-11e8-8319-9e59a109495d.png)

如图，cdoj的数组之前的语法都是 A_{i}这种，但是lutece的markdown无法识别

**Comment by LaPluses** [comment]
This is not Lutece markdown parser bug, for CDOJ, A_{i} was written as A\_{i} to escape _ character, currently Lutece do not needs to add \ to escape _.
