### ISSUE TITLE
点击主页的Honor按钮没反应

### ISSUE THREAD

**Issue by withlqs** [lutece-awesome/lutece-frontend#83]
点击主页的Honor按钮没反应，柱爷表示这是个Bug。

请修复。

**Comment by LaPluses** [comment]
Compared with others, this enhancement still in low priority.

**Comment by withlqs** [comment]
点了button没反应，怎么是enhancement呢？
就算是enhancement，为什么要close？其他的enhancement都没有close

我为柱爷鸣不平！
mozhu.today ！
